In [1]:
import numpy as np

In [18]:
array = np.array([[1, 2, 3, 4, 5, 6]]).T
weights = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
print(array)
print(weights)
new = np.array([np.dot(weights, array[: , 0])]).T

print(new)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[[91]
 [91]
 [91]
 [91]
 [91]]
